from enum import StrEnum


class TripStatus(StrEnum):
    PLANNED = "PLANNED"
    HEALTHY = "HEALTHY"
    AT_RISK = "AT_RISK"
    RECOVERED = "RECOVERED"
    CLOSED = "CLOSED"


class IncidentStatus(StrEnum):
    RECEIVED = "RECEIVED"
    ANALYZING = "ANALYZING"
    PLANNING = "PLANNING"
    NOTIFYING = "NOTIFYING"
    EXECUTING_AUTO = "EXECUTING_AUTO"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    EXECUTING = "EXECUTING"
    EXECUTING_APPROVED = "EXECUTING_APPROVED"
    VERIFYING = "VERIFYING"
    RECOVERED = "RECOVERED"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    NEEDS_ATTENTION = "NEEDS_ATTENTION"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ActionStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    LEASED = "LEASED"
    SUCCEEDED = "SUCCEEDED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_TERMINAL = "FAILED_TERMINAL"
    VERIFYING = "VERIFYING"
    VERIFIED = "VERIFIED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    SKIPPED = "SKIPPED"
    SUPERSEDED = "SUPERSEDED"


class ActionAttemptOutcome(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    RECONCILED = "RECONCILED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_TERMINAL = "FAILED_TERMINAL"


class RetryClass(StrEnum):
    NONE = "NONE"
    RETRYABLE = "RETRYABLE"
    TERMINAL = "TERMINAL"
    UNKNOWN = "UNKNOWN"


class ActionSafetyClass(StrEnum):
    INTERNAL_REVERSIBLE = "INTERNAL_REVERSIBLE"
    EXTERNAL_REVERSIBLE = "EXTERNAL_REVERSIBLE"
    FINANCIAL = "FINANCIAL"
    IRREVERSIBLE = "IRREVERSIBLE"
    AMBIGUOUS = "AMBIGUOUS"


class ItemType(StrEnum):
    FLIGHT = "FLIGHT"
    TRANSFER = "TRANSFER"
    HOTEL_ARRIVAL = "HOTEL_ARRIVAL"
    ACTIVITY = "ACTIVITY"


class DependencyType(StrEnum):
    CONNECTION = "CONNECTION"
    FOLLOW_ON = "FOLLOW_ON"


class EventProcessingStatus(StrEnum):
    PROCESSING = "PROCESSING"
    RETRYABLE = "RETRYABLE"
    COMPLETED = "COMPLETED"


class ClaimKind(StrEnum):
    NEW = "NEW"
    RESUMED = "RESUMED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"


class PolicyMode(StrEnum):
    AUTO = "AUTO"
    ASK = "ASK"


class ActionCategory(StrEnum):
    CALENDAR = "CALENDAR"
    SERVICE_MESSAGE = "SERVICE_MESSAGE"
    REVERSIBLE_CHANGE = "REVERSIBLE_CHANGE"
    FLIGHT_RECOVERY = "FLIGHT_RECOVERY"
    TRANSFER = "TRANSFER"


class PolicyVerdict(StrEnum):
    AUTO_APPROVED = "AUTO_APPROVED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"


class PolicyReasonCode(StrEnum):
    AMBIGUOUS = "AMBIGUOUS"
    IRREVERSIBLE = "IRREVERSIBLE"
    PENALTY_BEARING = "PENALTY_BEARING"
    MAJOR_ITINERARY_CHANGE = "MAJOR_ITINERARY_CHANGE"
    CALENDAR_POLICY_ASK = "CALENDAR_POLICY_ASK"
    SERVICE_MESSAGE_POLICY_ASK = "SERVICE_MESSAGE_POLICY_ASK"
    REVERSIBLE_CHANGE_POLICY_ASK = "REVERSIBLE_CHANGE_POLICY_ASK"
    AUTOMATIC_SPENDING_DISABLED = "AUTOMATIC_SPENDING_DISABLED"
    SPENDING_LIMIT_EXCEEDED = "SPENDING_LIMIT_EXCEEDED"
    UNSUPPORTED_CURRENCY = "UNSUPPORTED_CURRENCY"
    AUTO_ALLOWED = "AUTO_ALLOWED"


class PlanStatus(StrEnum):
    CURRENT = "CURRENT"
    SUPERSEDED = "SUPERSEDED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    DECLINED = "DECLINED"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"


class WorkflowCommandType(StrEnum):
    START_RECOVERY = "START_RECOVERY"
    CONTINUE_WORKFLOW = "CONTINUE_WORKFLOW"
    RESUME_AFTER_APPROVAL = "RESUME_AFTER_APPROVAL"
    RETRY_ACTION = "RETRY_ACTION"
    EXPIRE_APPROVAL = "EXPIRE_APPROVAL"
    REPLAN = "REPLAN"


class OutboxStatus(StrEnum):
    PENDING = "PENDING"
    PUBLISHED = "PUBLISHED"


class WorkflowCommandStatus(StrEnum):
    LEASED = "LEASED"
    COMPLETED = "COMPLETED"


class OnboardingStep(StrEnum):
    PROMISE = "PROMISE"
    CALENDAR = "CALENDAR"
    SERVICE_MESSAGES = "SERVICE_MESSAGES"
    REVERSIBLE_CHANGES = "REVERSIBLE_CHANGES"
    SPENDING = "SPENDING"
    BOUNDARY = "BOUNDARY"
    SUMMARY = "SUMMARY"
    COMPLETE = "COMPLETE"
